### ISSUE TITLE
请教与 openai/Whisper 的区别

### ISSUE THREAD

**Issue by Iceber** [Spr-Aachen/EVT-Core-Whisper#1]
你好，请教一下问什么独立出 Whisper 库，而不是将代码一起放到 EVT 主库中，看起来 EVT-Core-Whisper 的代码并不是很多

另外就是 load_model 函数与 whisper 一致，为什么不直接使用调用 whisper 的 [load_model](https://github.com/openai/whisper/blob/eab8d920edf3947294c466f3912c24ed4b191264/whisper/__init__.py#L72) 函数呢

https://github.com/Spr-Aachen/EVT-Core-Whisper/blob/ece7fe6b2be791615ec18f5090dcebb886e39b4b/Transcribe.py#L77

**Comment by Spr-Aachen** [comment]
1. 将Whisper库独立为submodule的形式是为了方便管理，因为有未来更新、替换/引入fast_whisper等第三方项目的打算所以不排除扩大代码量的可能性
2. 不是load_model的原因啦，相比于官方库这边主要做的改动就是对输出的srt文本格式做了替换以适应TTS模型训练所需要的数据集格式，其它的基本照搬官方的代码（已经很久没更新了）

**Comment by Iceber** [comment]
@Spr-Aachen 非常感谢
